version: '3.8'

services:
  app:
    image: laravelsail/php82-composer
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - appnet

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
